/**
 * DLWYC Check-In QR code helpers.
 *
 * A check-in QR pass encodes exactly two things (per the design):
 *   1. the EVENT ID     (e.g. "evt-camp")
 *   2. the attendee's OWN unique ID (e.g. "DLW/04/2026/0001")
 *
 * Wire format (plain text, safe in any QR scanner):
 *   DLWYC-CHKIN|<eventId>|<uniqueId>
 *
 * A JSON object { "eventId": ..., "uniqueId": ... } is also accepted when
 * parsing, so QRs generated by other tools with the same fields still work.
 */

export const QR_PREFIX = 'DLWYC-CHKIN';

/** Build the QR text for an attendee's pass to a specific event. */
export function buildQrPayload(eventId, uniqueId) {
  return `${QR_PREFIX}|${(eventId || '').trim()}|${(uniqueId || '').trim()}`;
}

/**
 * Parse raw scanned text into { eventId, uniqueId }.
 * Returns null when the text is not a DLWYC check-in code.
 */
export function parseQrPayload(raw) {
  const text = (raw || '').trim();
  if (!text) return null;

  // JSON form: {"eventId":"...","uniqueId":"..."}
  if (text.startsWith('{')) {
    try {
      const obj = JSON.parse(text);
      const eventId = String(obj.eventId || obj.event_id || obj.event || '').trim();
      const uniqueId = String(obj.uniqueId || obj.uid || obj.userId || '').trim();
      if (eventId || uniqueId) return { eventId, uniqueId };
      return null;
    } catch {
      return null;
    }
  }

  const parts = text.split('|').map((s) => s.trim());
  if (parts.length >= 3 && parts[0].toUpperCase() === QR_PREFIX) {
    return { eventId: parts[1], uniqueId: parts[2] };
  }
  // Lenient: prefix + uniqueId only (no event) — the station guard still applies.
  if (parts.length === 2 && parts[0].toUpperCase() === QR_PREFIX && parts[1]) {
    return { eventId: '', uniqueId: parts[1] };
  }
  return null;
}
