/**
 * DLWYC Check-In QR code helpers.
 *
 * A check-in QR pass encodes exactly two things (per the design):
 *   1. the attendee's FULL NAME (e.g. "Grace Osei")
 *   2. the EVENT ID           (e.g. "evt-camp")
 *
 * Wire format (plain text, safe in any QR scanner):
 *   DLWYC-CHKIN|<fullName>|<eventId>
 *
 * The attendee is resolved by name WITHIN that event (case- and
 * whitespace-insensitive) by the backend. If two attendees in the same event
 * share the name, the scan is rejected as `ambiguous` — never guessed.
 *
 * Legacy formats are still accepted when scanning (resolved by uniqueId —
 * a uniqueId in the payload always wins over the name):
 *   DLWYC-CHKIN|<eventId>|<uniqueId>
 *   DLWYC-CHKIN|<fullName>|<eventId>|<uniqueId>
 *   DLWYC-CHKIN|<uniqueId>
 *
 * A JSON object { "fullName": ..., "eventId": ... } (or the legacy
 * { "eventId": ..., "uniqueId": ... }) is also accepted when parsing, so QRs
 * generated by other tools with the same fields still work.
 */

export const QR_PREFIX = 'DLWYC-CHKIN';

/** Build the QR text for an attendee's pass to a specific event. */
export function buildQrPayload(fullName, eventId) {
  // A literal "|" in a name would corrupt the pipe-delimited payload.
  const name = (fullName || '').replace(/\|/g, ' ').trim();
  return `${QR_PREFIX}|${name}|${(eventId || '').trim()}`;
}

/**
 * Parse raw scanned text into a descriptor:
 *   { format: 'name',     fullName, eventId }            — current format
 *   { format: 'uniqueId', uniqueId, eventId, fullName }  — legacy formats
 * Returns null when the text is not a DLWYC check-in code.
 *
 * Note: a 3-part payload is parsed as the current name format; if it was
 * actually a legacy `eventId|uniqueId` code the backend still resolves it
 * (it disambiguates against the database — a matching uniqueId wins).
 */
export function parseQrPayload(raw) {
  const text = (raw || '').trim();
  if (!text) return null;

  // JSON form: {"fullName":"...","eventId":"..."} or legacy {"eventId":"...","uniqueId":"..."}
  if (text.startsWith('{')) {
    try {
      const obj = JSON.parse(text);
      const uniqueId = String(obj.uniqueId || obj.uid || obj.userId || '').trim();
      const fullName = String(obj.fullName || obj.name || '').trim();
      const eventId = String(obj.eventId || obj.event_id || obj.event || '').trim();
      if (uniqueId) return { format: 'uniqueId', uniqueId, eventId, fullName };
      if (fullName) return { format: 'name', fullName, eventId, uniqueId: '' };
      return null;
    } catch {
      return null;
    }
  }

  const parts = text.split('|').map((s) => s.trim());
  if (parts[0].toUpperCase() !== QR_PREFIX) return null;

  // Legacy lenient form: prefix + uniqueId only (no event).
  if (parts.length === 2 && parts[1]) {
    return { format: 'uniqueId', uniqueId: parts[1], eventId: '', fullName: '' };
  }
  // Current format: prefix + fullName + eventId.
  if (parts.length === 3 && parts[1] && parts[2]) {
    return { format: 'name', fullName: parts[1], eventId: parts[2], uniqueId: '' };
  }
  // Legacy: prefix + fullName + eventId + uniqueId (uniqueId wins).
  if (parts.length >= 4 && parts[1] && parts[2] && parts[3]) {
    return { format: 'uniqueId', uniqueId: parts[3], eventId: parts[2], fullName: parts[1] };
  }
  return null;
}
