/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchdeaconLeadersRouteImport } from './routes/archdeacon-leaders'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard/events/$id'

const SignupLazyRouteImport = createFileRoute('/signup')()
const ResetPasswordLazyRouteImport = createFileRoute('/resetPassword')()
const ForgotPasswordLazyRouteImport = createFileRoute('/forgotPassword')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardSettingsLazyRouteImport = createFileRoute(
  '/dashboard/settings',
)()
const DashboardCodesLazyRouteImport = createFileRoute('/dashboard/codes')()
const DashboardEventsIndexLazyRouteImport =
  createFileRoute('/dashboard/events/')()

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const ResetPasswordLazyRoute = ResetPasswordLazyRouteImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/resetPassword.lazy').then((d) => d.Route))
const ForgotPasswordLazyRoute = ForgotPasswordLazyRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgotPassword.lazy').then((d) => d.Route),
)
const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchdeaconLeadersRoute = ArchdeaconLeadersRouteImport.update({
  id: '/archdeacon-leaders',
  path: '/archdeacon-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardSettingsLazyRoute = DashboardSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/settings.lazy').then((d) => d.Route),
)
const DashboardCodesLazyRoute = DashboardCodesLazyRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/codes.lazy').then((d) => d.Route),
)
const DashboardEventsIndexLazyRoute =
  DashboardEventsIndexLazyRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/events/index.lazy').then((d) => d.Route),
  )
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/events/$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archdeacon-leaders': typeof ArchdeaconLeadersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/workforce': typeof WorkforceRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/resetPassword': typeof ResetPasswordLazyRoute
  '/signup': typeof SignupLazyRoute
  '/dashboard/codes': typeof DashboardCodesLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/': typeof DashboardEventsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archdeacon-leaders': typeof ArchdeaconLeadersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/workforce': typeof WorkforceRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/resetPassword': typeof ResetPasswordLazyRoute
  '/signup': typeof SignupLazyRoute
  '/dashboard/codes': typeof DashboardCodesLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events': typeof DashboardEventsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archdeacon-leaders': typeof ArchdeaconLeadersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/workforce': typeof WorkforceRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/resetPassword': typeof ResetPasswordLazyRoute
  '/signup': typeof SignupLazyRoute
  '/dashboard/codes': typeof DashboardCodesLazyRoute
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/': typeof DashboardEventsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archdeacon-leaders'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/gallery'
    | '/leadership'
    | '/login'
    | '/workforce'
    | '/forgotPassword'
    | '/resetPassword'
    | '/signup'
    | '/dashboard/codes'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archdeacon-leaders'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/leadership'
    | '/login'
    | '/workforce'
    | '/forgotPassword'
    | '/resetPassword'
    | '/signup'
    | '/dashboard/codes'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/events/$id'
    | '/dashboard/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archdeacon-leaders'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/gallery'
    | '/leadership'
    | '/login'
    | '/workforce'
    | '/forgotPassword'
    | '/resetPassword'
    | '/signup'
    | '/dashboard/codes'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchdeaconLeadersRoute: typeof ArchdeaconLeadersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  LeadershipRoute: typeof LeadershipRoute
  LoginRoute: typeof LoginRoute
  WorkforceRoute: typeof WorkforceRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  ResetPasswordLazyRoute: typeof ResetPasswordLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetPassword': {
      id: '/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof ResetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archdeacon-leaders': {
      id: '/archdeacon-leaders'
      path: '/archdeacon-leaders'
      fullPath: '/archdeacon-leaders'
      preLoaderRoute: typeof ArchdeaconLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/codes': {
      id: '/dashboard/codes'
      path: '/codes'
      fullPath: '/dashboard/codes'
      preLoaderRoute: typeof DashboardCodesLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCodesLazyRoute: typeof DashboardCodesLazyRoute
  DashboardSettingsLazyRoute: typeof DashboardSettingsLazyRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardEventsIdRoute: typeof DashboardEventsIdRoute
  DashboardEventsIndexLazyRoute: typeof DashboardEventsIndexLazyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCodesLazyRoute: DashboardCodesLazyRoute,
  DashboardSettingsLazyRoute: DashboardSettingsLazyRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardEventsIdRoute: DashboardEventsIdRoute,
  DashboardEventsIndexLazyRoute: DashboardEventsIndexLazyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchdeaconLeadersRoute: ArchdeaconLeadersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  LeadershipRoute: LeadershipRoute,
  LoginRoute: LoginRoute,
  WorkforceRoute: WorkforceRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  ResetPasswordLazyRoute: ResetPasswordLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
