/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SignupLazyRouteImport = createFileRoute('/signup')()
const ResetPasswordLazyRouteImport = createFileRoute('/resetPassword')()
const ForgotPasswordLazyRouteImport = createFileRoute('/forgotPassword')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardEventsIndexLazyRouteImport =
  createFileRoute('/dashboard/events/')()
const DashboardEventsIdLazyRouteImport = createFileRoute(
  '/dashboard/events/$id',
)()

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const ResetPasswordLazyRoute = ResetPasswordLazyRouteImport.update({
  id: '/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/resetPassword.lazy').then((d) => d.Route))
const ForgotPasswordLazyRoute = ForgotPasswordLazyRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgotPassword.lazy').then((d) => d.Route),
)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardEventsIndexLazyRoute =
  DashboardEventsIndexLazyRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/events/index.lazy').then((d) => d.Route),
  )
const DashboardEventsIdLazyRoute = DashboardEventsIdLazyRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/events/$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/resetPassword': typeof ResetPasswordLazyRoute
  '/signup': typeof SignupLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/events/$id': typeof DashboardEventsIdLazyRoute
  '/dashboard/events/': typeof DashboardEventsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/resetPassword': typeof ResetPasswordLazyRoute
  '/signup': typeof SignupLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/events/$id': typeof DashboardEventsIdLazyRoute
  '/dashboard/events': typeof DashboardEventsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/forgotPassword': typeof ForgotPasswordLazyRoute
  '/resetPassword': typeof ResetPasswordLazyRoute
  '/signup': typeof SignupLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/events/$id': typeof DashboardEventsIdLazyRoute
  '/dashboard/events/': typeof DashboardEventsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/forgotPassword'
    | '/resetPassword'
    | '/signup'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/forgotPassword'
    | '/resetPassword'
    | '/signup'
    | '/dashboard'
    | '/dashboard/events/$id'
    | '/dashboard/events'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/forgotPassword'
    | '/resetPassword'
    | '/signup'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  ResetPasswordLazyRoute: typeof ResetPasswordLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetPassword': {
      id: '/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof ResetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardEventsIdLazyRoute: typeof DashboardEventsIdLazyRoute
  DashboardEventsIndexLazyRoute: typeof DashboardEventsIndexLazyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardEventsIdLazyRoute: DashboardEventsIdLazyRoute,
  DashboardEventsIndexLazyRoute: DashboardEventsIndexLazyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  ResetPasswordLazyRoute: ResetPasswordLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
